### PR TITLE
2022 social insurance parameters

### PR DESCRIPTION
**Pull request by Eric-Sommer**
Implement changes from SVRechGrV becoming effective in 2022 (https://www.buzer.de/SVRechGrV_2022.htm), plus adding one parameter from 2021.

### CODE REVIEW

**Review by ChristianZimpelmann — CHANGES_REQUESTED** [review]
Looks good!

I think we should do all changes for 2022 in one PR. So let's merge #319 to this branch and also take care at the other changes taking place. Or was that already everything? Can you have a look, @Eric-Sommer? Otherwise, I can take over.

Also don't forget to mention your contribution in `changes.rst`.

**Comment by Eric-Sommer** [comment]
I haven't found any other changes to 2022, apart from these and #319. Are you aware of anything else, @mjbloemer?

**Comment by mjbloemer** [comment]
Happy new year!

Only on SSC:

- PV Zusatzbeitrag Kinderlose increased from 0.0025 to 0.0035. See Artikel 2 G. v. 11.07.2021 BGBl. I S. 2754.
- KV Zusatzbeitrag is still 1.6 for 2022 but defined by a separate law for 2022: same as previous comment, Gesundheitsversorgungsweiterentwicklungsgesetz. 19.07.2021, Nr 44 (2021), BGBl. Teil I https://offenegesetze.de/suche?q=%221%2C3+Prozent%22&year=2021 G. v.  19.07.2021 BGBl. I S. 2754. BTW: Why is this Zusatzbeitrag still treated as two parameters (AG and AN) and the split (50-50 or 100-0 in other years) not done in python? I would always denote parameters in the yaml files as close as possible to the law.
- `ag_abgaben_geringf` maybe also changed: Insolvenzgeldumlagesatzverordnung 2022 §2). See https://www.minijob-zentrale.de/DE/01_minijobs/02_gewerblich/01_grundlagen/01_450_euro_gewerbe/02_abgaben_gewerbliche/node.html

On #319 I will comment there. (There are more parameters changes than SSC and ALG2, but I will have to check what is already in GETTSIM or can be found in a different PR).

**Comment by ChristianZimpelmann** [comment]
I fixed the checks in #319. Either merge this PR to this branch. Or merge #319 to `main` and `main` to `sozvers_2022` afterwards

**Comment by Eric-Sommer** [comment]
>     * PV Zusatzbeitrag Kinderlose increased from 0.0025 to 0.0035. See Artikel 2 G. v. 11.07.2021 BGBl. I S. 2754.

implemented now, thanks!
 
>     * KV Zusatzbeitrag is still 1.6 for 2022 but defined by a separate law for 2022: same as previous comment, Gesundheitsversorgungsweiterentwicklungsgesetz. 19.07.2021, Nr 44 (2021), BGBl. Teil I https://offenegesetze.de/suche?q=%221%2C3+Prozent%22&year=2021 G. v.  19.07.2021 BGBl. I S. 2754. 

Since all the main contribution rates have been merged in one entry `soz_vers_beitr`, all legal references have vanished. They are also not terribly useful because the yearly changes are often not written in the SGBs.

> BTW: Why is this Zusatzbeitrag still treated as two parameters (AG and AN) and the split (50-50 or 100-0 in other years) not done in python? I would always denote parameters in the yaml files as close as possible to the law.

path dependency, I guess... I agree that this is suboptimal, but maybe for a separate PR.

>     * `ag_abgaben_geringf` maybe also changed: Insolvenzgeldumlagesatzverordnung 2022 §2). See https://www.minijob-zentrale.de/DE/01_minijobs/02_gewerblich/01_grundlagen/01_450_euro_gewerbe/02_abgaben_gewerbliche/node.html

We don't model Minijob-Umlagen. The other paramaters have not changed, I added some legal references

**Comment by ChristianZimpelmann** [comment]
> KV Zusatzbeitrag is still 1.6 for 2022

Do you mean 1.3?

I agree that it would make sense to split up KV Allgemeiner Beitragssatz and KV Zusatzbeitrag, but doesn't have to be this PR.

I just fixed a type and merged `main`

**Review by ChristianZimpelmann — APPROVED** [review]

**Pull request merged**
