### PR TITLE
Implement mehrbedarf for arbeitsl_geld_2

### LINKED ISSUE #341: Implement `mehrbedarf_behinderung_m_hh` for ALG 2
### Current and desired situation

`mehrbedarf_behinderung_m_hh` implemented for Grundsicherung im Alter, but not for ALG 2.

### Proposed implementation

Similarly to `mehrbedarf_behinderung_m_hh` for Grundsicherung im Alter. Might even be able to use the same parameters and function?

### PR DESCRIPTION
**Pull request by MaxBlesch**
### What problem do you want to solve?

Closes #341. Implement mehrbedarf and test.

### Todo

- [ ] Implement `mehrbedarf` and parameter.
- [ ] Implement test.
- [ ] Track changes `CHANGES.md`.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Some useful discussion in #372

**Comment by hmgaudecker** [comment]
@ChristianZimpelmann @MaxBlesch @Eric-Sommer -- do you have a sense how far along the way of a serious implementation this has come? Tests are missing, it seems and per the discussion in #372, the most important thing will be to add a differentiation between getting benefits under SGB II (`arbeitsl_geld_2`) or SGB XII (`grunds_bei_erwerbsminderung`).

I am getting the feeling this is opening a can of worms more than anything. If so, I would close this one as well and add the gist of the discussions to #341, enhancing its scope to add  `grunds_bei_erwerbsminderung`.

**Comment by ChristianZimpelmann** [comment]
I am not sure how much work is left to finish the PR and hopw @MaxBlesch has a better overview here.

I like your proposal, @hmgaudecker. But if PR can be finished soon, we could also add it. Assigning Mehrbedarf based on the wrong SGB does not seem worse than assigning no Mehrbedarf at all.

**Comment by MaxBlesch** [comment]
I can not really estimate how much time is needed to finish this PR. There is definitely still more to do than there is done already. So, I would agree with @hmgaudecker and close this PR. When the time has come to tackle #341, the main contributions made so far in this PR, can be easily looked up and re-implemented!

**Comment by hmgaudecker** [comment]
Thanks, will do!

**Comment by hmgaudecker** [comment]
I added the gist of this and the discussion from #372 to [#341](https://github.com/iza-institute-of-labor-economics/gettsim/issues/341#issuecomment-1373168832). Can safely close now.

**Pull request closed without merging**
