### PR TITLE
Fix Links in How-to Guides and Tutorials

### PR DESCRIPTION
**Pull request by davpahl**
Fix all the links in How-to Guides and Tutorials as discussed in #264 .

**Todo**

- [x] Fix links in How-to Guides
- [x] understand what exactly is not working in tutorials
- [x] link nodes of DAGs to documentation correctly

### CODE REVIEW

**Comment by davpahl** [comment]
@ChristianZimpelmann, the links in the How-to Guides should be working now. 

In the development version, the links from the nodes of the DAGs to the documention do not work, because
-  ``/gettsim_objects`` seems to be missing in the ``_create_url``-function of ``visualization.py``
- the version of gettsim is specified as 0.4 in the ``__init__.py``, but is called 0.4.0 on the website

Would 0.4.0 be the correct name of the version in the ``__init__.py``?

**Comment by ChristianZimpelmann** [comment]
Thank you @davpahl great work!

You can add your contribution to `CHANGES.rst`.

You were absolutely right why the nodes have the wrong links! I changed it in my commit now. The problem, however, seems to be that I cannot run the notebook with the changes implemented before publishing a new version. Trying to figure out a solution..

**Comment by ChristianZimpelmann** [comment]
It should be updated now!

@davpahl, can you please double check and update CHANGES.rst? Then we can merge.

**Comment by davpahl** [comment]
Yes, everything looks good to me in the version created by this pull request now.

**Review by ChristianZimpelmann — APPROVED** [review]

**Pull request merged**
