### PR TITLE
Migration of the parameter database from xls to yaml.

### LINKED ISSUE #31: Datatype of params
We need to discuss how to move away from excel sheets.

### PR DESCRIPTION
**Pull request by mjbloemer**
Work in Progress - do not merge!

When merged, his PR migrates the binary param.xls to a param.yaml. Closes #31.

This PR includes the following changes:
- [X] A full conversion of parameters and annotations from the original param.xls
- [X] Remove the old param.xls
- [x] The necessary changes related to database read-in

This PR explicitly does not include the following changes:
- general cleanup of strings
- correction of values

No information is added, removed or modified, except:
- Add group names based on the original annotations. E.g. `[ALG2]` which was part of the xls column "comment_DE" are now stored under the key `group: alg2`. 
- Removed usernames and hostnames from comment/annotation strings
- dates are stored as `yyyy-01-01` irrespective of the actual starting date
- dropped six duplicate definitions: `wgmax*_m_st3`

After merge, I will open separate issues on cleanup and fixing of the param.yaml, these will be:
- fix values
- fix start dates to precise day
- cleanup of name, description and values
- translation task for these strings
- check group names
- sorting by groups
- assign unit key (euro, dm, one, percent, thousand..)
- assign period key (month, year..)

Please comment in this PR on aspects specific to this implementation. When it comes to alternative implementations leave the discussion in #31.

The automated parameter documentation is addressed in #44.

### CODE REVIEW

**Comment by MaxBlesch** [comment]
I added nans for not existing values. Right now the code relies for years a policy would actually not exist on nans. A example for this is https://github.com/iza-institute-of-labor-economics/gettsim/blob/1633e1e08f7ac895cb18b1397633e37a5a3e4551/gettsim/taxes/zve.py#L288 .

I think we should in the end have code, which doesn't calls variables for years in which they don't exist. Right now we can't gurantee that the code spits out the right values for every possible year.

@mjbloemer any feedback on the current implementation?

**Comment by MaxBlesch** [comment]
@mjbloemer gave me some private feedback. Do you have anything @hmgaudecker ? Otherwise I'll merge!

**Comment by hmgaudecker** [comment]
This is great and an obvious improvement without changing functionality or pinning down long term decisions.

So do not worry about me. Not like I am the dictator here or anything, though strong opinions might sometimes give that impression... 😉

**Comment by MaxBlesch** [comment]
Ok, thanks :)

**Pull request merged**
