### PR TITLE
Fix Bemessungsgrundlage for ges_krankenv Selbstständige

### LINKED ISSUE #174: Revise SSC GKV for self employed
### Bug description

* For self employed who are in GKV, is there really a general cap at 75% of *Bezugsgröße*? This is how it is modeled in https://github.com/iza-institute-of-labor-economics/gettsim/blob/b46acc07ae130215f7b4838acfd83dc4c1d2fd9e/gettsim/soz_vers.py#L117-L142
* This cap at 75% of *Bezugsgröße* might still be relevant for individuals who are not mainly self employed (less than 20 hour of work in self employed), see e.g.: https://selbststaendigkeit.de/sites/default/files/merkblatt_-_die_krankenversicherung_fuer_nebenberuflich_selbststaendige.pdf
* Mindestbemessungsgrundlage for self employed is missing, see [§ 240 SGB V (4)](https://www.buzer.de/240_SGB_V.htm). E.g. Mindestbemessungsgrundlage: 1.061,67 (from [example](https://www.bundesgesundheitsministerium.de/beitraege-und-tarife.html#c4754)) can be calculated as `bezgr_w/90 * 30 = 3185/90 * 30 = 1061,67`.

### LINKED ISSUE #404: Mindest­bei­trag ges.Krankenversicherung für haupt­be­ruf­lich Selb­stän­dige
### Current and desired situation

Currently when calculating the health insurance contributions for Selbstständige, the Beitragssatz is applied to the self employed income from -inf to the Beitragsbemessungsgrenze. This causes unwanted behaviour if the income is below zero, as a negative value is calculated for the health insurance contribution.

The real life implementation includes a [Mindestbeitrag](https://www.tk.de/techniker/leistungen-und-mitgliedschaft/informationen-versicherte/veraenderung-berufliche-situation/versichert-als-selbststaendige/haeufige-fragen-fuer-selbststaendige/hoehe-herleitung--mindestbeitrag-hauptberuflich-selbststaendige-2007008) for Selbstständige, which is calculated on the basis of a Mindesteinkommen on which the Beitragssatz is applied.

The Mindesteinkommen is [derived from](https://dejure.org/gesetze/SGB_V/240.html#Abs4:S1) the [Bezugsgröße](https://de.wikipedia.org/wiki/Bezugsgr%C3%B6%C3%9Fe). The Parameter Bezugsgröße already exists in GETTSIM. 

### Proposed implementation

To implement this, Mindesteinkommen has to be calculated. Then `max(mindesteinkommen, eink_selbst_m)` chooses if the Beitragssatz is applied to the Mindesteinkommen or the actual income.

### PR DESCRIPTION
**Pull request by JHermann99**
### What problem do you want to solve?

Closes #404 
Closes #174 

### Todo

- [x] Introduce Mindesteinkommen
   - [x] calculate Mindesteinkommen
- [x] check upper limit of the Bemessungsgrundlage

### CODE REVIEW

**Comment by JHermann99** [comment]
Closes #404

**Comment by JHermann99** [comment]
I just noticed, that the issue of mindesteinkommen has already been raised in #174 and a corresponding Zulip discussion, but does not seem to have been fixed. Additionally, the upper limit of 0.75*Bezugsgröße was also questioned. I also found no reference to this. Therefore I propose to implement the normal Beitragsbemessungsgrenze as described [here](https://www.tk.de/techniker/leistungen-und-mitgliedschaft/informationen-versicherte/veraenderung-berufliche-situation/versichert-als-selbststaendige/haeufige-fragen-fuer-selbststaendige/wie-kommt-mein-beitrag-als-selbststaendiger-zustande-2011022).

**Comment by JHermann99** [comment]
Hi @hmgaudecker, unfortunately I was unable to automatically merge main into my branch and will not have the time to deal with this until next year. I have added you as a collaborator to my repo if you would like to get this done now. Otherwise I will do it early January. I am unsure how to move my branch to this repo, so if you have a good tutorial please let me know!

**Comment by hmgaudecker** [comment]
Cool, did this now since I had been working on that stuff the last couple of days, so many memories were still fresh.

Unfortunately, `main` changed quite heavily when it comes to the tests, unrelated to the stuff I had done. I left your version of `sozialv_beitr.csv` in the main directory so you can quickly compare whatever changes are necessary to `src/_gettsim_tests/test_data/sozialv_beitr.csv` (that is the same version as in main currently).

Next year is fine, of course !

**Comment by hmgaudecker** [comment]
Hi @JHermann99, do you have an idea when you might have a chance to take a look again? Happy to take over, too, if you will not be able to find the time (ideally after a short introduction into the test data).

**Review by hmgaudecker — APPROVED** [review]
Thanks a ton!

**Pull request merged**
