### PR TITLE
Adjusting test data to the correct data type

### PR DESCRIPTION
**Pull request by LauraGergeleit**
### What problem do you want to solve?

Addressing #430 by adjusting data type of test data in csv-files. 
Note: the respective columns have to be imported as Text-Datatype, when re-importing the csv-file to Excel, to ensure that the format remains the same.

### CODE REVIEW

**Comment by ChristianZimpelmann** [comment]
Thanks!

> Note: the respective columns have to be imported as Text-Datatype, when re-importing the csv-file to Excel, to ensure that the format remains the same.

I am afraid future users will forget about this and sooner or later the formatting of numbers as floats or integers respectively will be lost again if we only change the .csv-file.

Two alternatives would be:
- to run `_convert_data_to_correct_types` after importing the .csv in each test. (with a new keyword-argument which disables warnings)
- to filter out these kind of warnings when running tests.

Note, that we won't have this problem anymore once we addressed #62 . So we just need a temporary fix for now. 

@hmgaudecker, what do you think?

**Comment by hmgaudecker** [comment]
We should just tackle #62 then (@LauraGergeleit ?). Make a note in the PR that this will be addressed by the fix, too

**Comment by ChristianZimpelmann** [comment]
Note: I linked an old, already closed issue, but adjusted it now in the messages above: the correct one is #282.

Let's continue the discussion over there.

**Comment by hmgaudecker** [comment]
Looks already much better! Helped me spot a pending deprecation we should tackle: https://github.com/iza-institute-of-labor-economics/gettsim/issues/468

As a New Year's Resolution, let's work on keeping PRs shorter. So just continue with the (few) remaining conversion warnings as you did above and tackle the yaml conversion in a subsequent issue. Having the correct types in the csv should actually be helpful  for that. And let's get started soon enough so that not too many people have a chance to commit wrong data types :wink:

**Comment by LauraGergeleit** [comment]
> As a New Year's Resolution, let's work on keeping PRs shorter. So just continue with the (few) remaining conversion warnings as you did above and tackle the yaml conversion in a subsequent issue. Having the correct types in the csv should actually be helpful for that. And let's get started soon enough so that not too many people have a chance to commit wrong data types 😉

I adjusted the data types for the remaining csv-files and will tackle the yaml conversion in a new PR soon

**Comment by hmgaudecker** [comment]
Beautiful, thanks a lot!!! 

Immediately you start seeing other stuff when the test suite runs through, see #485

**Pull request merged**
