### PR TITLE
Harmonise hooks with estimagic & friends

### PR DESCRIPTION
**Pull request by hmgaudecker**
Following up on #450, others (@janosg @tobiasraabe @timmens) much improved upon what I had been doing in estimagic, pytask, and elsewhere. This PR ports those changes to GETTSIM.

Most importantly, flake8 is replaced by ruff.

### CODE REVIEW

**Review by hmgaudecker — COMMENTED** [review]
Just a reminder that I double-checked everything.

**Comment by hmgaudecker** [comment]
*(failure of pre-commit.ci is due to being slow in updating ruff, just ignore)*

**Review by ChristianZimpelmann — APPROVED** [review]
Looks great!

I just don't like that adding lists seem to be flagged now. In my opinion, the alternative makes the code less intuitive (for non-Python experts).

**Comment by hmgaudecker** [comment]
> I just don't like that adding lists seem to be flagged now. In my opinion, the alternative makes the code less intuitive (for non-Python experts).

Fair enough, the good thing is that these fixes happen automatically. So people can write it the way they find it intuitive and then it is applied by the hooks.

**Pull request merged**
